# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions



gym(scheme: 'FastlanePro', project: "FastlanePro.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')

#upload_to_testflight
altool(
        altool_username: ENV["imuneebali+4@gmail.com"],
        altool_password: ENV["Muneeb69"],
        altool_app_type: "ios",
        altool_ipa_path: "/Users/humayun/Desktop/Archive/FastlanePro.ipa",
        altool_output_format: "xml",
)
 
  end

end
