# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions



gym(scheme: 'FastlanePro', project: "FastlanePro.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')

    crashlytics(api_token: '625bae68c3112f09a74ca3a032a4c39248be5629',
             build_secret: '135ce89d62d3d2ddbc9bbcc6fa11c8ee08dc4d1953c1cad55f6ad73919fdb653',
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

 
  end

end
